replicaCount: 1

image:
  repository: accelerboat/squid
  pullPolicy: IfNotPresent
  tag: "5.2-22.04_beta"

imagePullSecrets: []

# This is to override the chart name.
fullnameOverride: "accelerboat-squid"

# Set resources as needed
resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 128Mi

# Node selector for scheduling
nodeSelector: {}

tolerations: []

# Pod anti-affinity: one pod per node
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app: accelerboat-squid
        topologyKey: "kubernetes.io/hostname"

# Set to true if needed
hostNetwork: true

# Squid config (customize as needed)
squidConf: |+
  acl all src all 
  http_access allow all
  http_port 2088
  cache_dir ufs /var/spool/squid 100 16 256
  forwarded_for on

service:
  type: ClusterIP
  port: 2088

# Additional volumes on the output Deployment definition.
volumes:
  - name: squid-conf
    configMap:
      name: squid-conf

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
  - name: squid-conf
    mountPath: /etc/squid/squid.conf
    subPath: squid.conf

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
